variables:
  DOCKER_BUILD_TOOL: kaniko
  OCI: dta
  DOCKER_FILE: CNF/Dockerfile
  # DOCKER_SNAPSHOT_IMAGE: "docker-public-unstable-hosted-cicd-nexus.rp-ocn.apps.ocn.infra.ftgroup/olb/${OCI}:$CI_COMMIT_REF_SLUG"
  DOCKER_BUILD_CACHE_DISABLED: "true"
  DOCKER_BUILD_ARGS: "--build-arg SRC_REPO_BRANCH=$CI_COMMIT_REF_NAME --build-arg SRC_REPO_USER=$SRC_REPO_USER --build-arg SRC_REPO_PWD=$SRC_REPO_PWD"
  GO_BUILD_MODE: application
  GO_SBOM_OPTS: "-main cmd/"
  CHECKMARX_PROJECTNAME: "CxServer/ORANGE/WIN/OINIS/2G6/Diameter-Translation-Agent"
  CHECKMARX_FORCE_SCAN: "False"
  SONAR_URL: "https://sqaas.dos.tech.orange"
  SONAR_HOST_URL: "https://sqaas.dos.tech.orange"
  SONAR_PROJECT_KEY: https://sqaas.dos.tech.orange/dashboard?id=win-oinis-olb-2g6-Diameter-Translation-Agent

include:
  - project: 'to-be-continuous/docker'
    ref: '5.13.2'
    file: '/templates/gitlab-ci-docker.yml'
  - project: "to-be-continuous/gitleaks"
    ref: "2.1"
    file: "templates/gitlab-ci-gitleaks.yml"
  - project: 'to-be-continuous/custom/checkmarx'
    ref: '2.3.1'
    file: '/templates/gitlab-ci-checkmarx.yml'
  - project: 'to-be-continuous/golang'
    ref: '4.11.0'
    file: '/templates/gitlab-ci-golang.yml'
  - project: 'to-be-continuous/sonar'
    ref: '4.2.2'
    file: '/templates/gitlab-ci-sonar.yml'

stages:
  - build
  - test
  - package-build
  - package-test
  - deploy
  - publish

docker-kaniko-build:
  stage: package-build
  rules:
    - if: $DOCKER_BUILD_TOOL == "kaniko"
      changes:
        - CNF/*
        - cmd/*
        - .gitlab-ci.yml
        - internal/*
        - pkg/*/*
      
docker-publish:
  stage: publish
  rules:
    - when: never

checkmarx:
  timeout: 6h

docker-trivy:
  allow_failure: true